name: Birdcage CI

env:
  MIX_ENV: test
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Elixir
        uses: actions/setup-elixir@v1
        with:
          elixir-version: "1.10.3" # Define the elixir version [required]
          otp-version: "22.3" # Define the OTP version [required]

      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-

      - name: Restore build cache
        uses: actions/cache@v2
        with:
          path: _build/test/
          key: ${{ runner.os }}-build-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-build-

      - name: Install dependencies
        run: |
          mix deps.get

      - name: Credo review
        uses: red-shirts/reviewdog-action-credo@v1
        with:
          github_token: ${{ secrets.github_token }}
          level: error
          reporter: github-pr-review

      - name: Credo check
        # run: mix credo --strict
        uses: red-shirts/reviewdog-action-credo@v1
        with:
          github_token: ${{ secrets.github_token }}
          level: error
          reporter: github-pr-check

      - name: Check code format
        run: mix format --check-formatted

      - name: Run tests
        run: mix coveralls.github

        # https://github.com/marketplace/actions/action-for-semantic-release
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 16
          branches: |
            [
              '+([0-9])?(.{+([0-9]),x}).x',
              'main',
              'next',
              'next-major',
              {
                name: 'beta',
                prerelease: true
              },
              {
                name: 'alpha',
                prerelease: true
              }
            ]
          extra_plugins: |
            @semantic-release/exec
            @semantic-release/changelog
            @semantic-release/github
            @semantic-release/git
